apiVersion: v1
kind: Service
metadata:
  name: MyApp-mysql
  labels:
    app: MyApp
spec:
  ports:
    - port: 3306
  selector:
    app: MyApp
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: MyApp-mysql-pv-claim
  labels:
    app: MyApp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyApp-mysql
  labels:
    app: MyApp
spec:
  selector:
    matchLabels:
      app: MyApp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: MyApp
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: MyApp-mysql
        env:
        - name: MYSQL_DATABASE
          value: "MyApp_db"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: MyApp-mysql-pass
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: MyApp-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: MyApp-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: MyApp-mysql-pv-claim