apiVersion: v1
kind: Service
metadata:
  name: MyApp-redis
  labels:
    app: MyApp
spec:
  ports:
    - port: 6379
  selector:
    app: MyApp
    tier: redis
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyApp-redis
  labels:
    app: MyApp
spec:
  selector:
    matchLabels:
      app: MyApp
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: MyApp
        tier: redis
    spec:
      containers:
      - image: redis:4-alpine
        name: redis
        ports:
        - containerPort: 6379
          name: redis